payapp/urls.py
from django.urls import path
from . import views

app_name = 'payapp'
urlpatterns = [
    path('', views.index, name="home"),
    path('about', views.about, name="about"),
    path('how', views.how, name="how"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('transactions', views.transactions, name='transactions'),
    path('make_payment', views.make_payment, name='make_payment'),
    path('request_payments', views.request_payment, name='request_payments'),
    path('notification', views.notification, name='notification'), 
    path('handle_payment_request/<int:request_id>/<str:action>/', views.handle_payment_request, name='handle_payment_request'),
    path('conversion/<str:currency1>/<str:currency2>/<amount>', views.convert_currency, name='convert_currency'),
]

webapps2024/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('payapp.urls')),
    path('accounts/', include('register.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title%}WEBapp Home{% endblock %}

{% block content %}

    <!-- about section -->
    <section class="about_section layout_padding">
        <div class="container">
            <div class="heading_container">
                <h2>
                About Cryptop
                </h2>
            </div>
            
            <div class="box">
                <div class="img-box">
                <img src="images/about-img.png" alt="">
                </div>
                <div class="detail-box">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniamLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                    eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim
                </p>
                <div class="btn-box">
                    <a href="">
                    Read More
                    </a>
                </div>
                </div>
            </div>
        </div>
    </section>
  <!-- end about section -->


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title%}WebApp{% endblock %}</title>

    <!-- slider stylesheet -->
    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

</head>
<body>

    <!-- header section strats -->
    <header class="header_section">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="{% url 'payapp:home' %}">
              <span>
                WEBapp
              </span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
  
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <div class="d-flex ml-auto flex-column flex-lg-row align-items-center">
                <ul class="navbar-nav  ">
                  <li class="nav-item {% if request.path == '/home' or request.path == '/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'payapp:home' %}">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item {% if request.path == '/about' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'payapp:about' %}"> About </a>
                  </li>
                  <li class="nav-item {% if request.path == '/how' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'payapp:how' %}"> How </a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'payapp:dashboard' %}"> Dashboard</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}"> Logout</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"> Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}"> Sign Up</a>
                  </li>
                  {% endif %}
                </ul>
                <div class="user_option">
                  <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                    <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
                  </form>
                </div>
              </div>
            </div>
          </nav>
        </div>
    </header>

    <div class="">
        {% block content %}
        {% endblock %}
    </div>

    <!-- info section -->
    <section class="info_section layout_padding">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <div class="info_contact">
              <div class="info_logo">
                <a href="index.html">
                  <span>
                    Cryptop
                  </span>
                </a>
              </div>
              <h5>
                Contact Us
              </h5>
              <div>
                <div class="img-box">
                  <img src="{% static 'images/location.png' %}" width="18px" alt="" />
                </div>
                <p>
                  Page when looking at its layou
                </p>
              </div>
              <div>
                <div class="img-box">
                  <img src="{% static 'images/phone.png' %}" width="18px" alt="" />
                </div>
                <p>
                  +01 1234567890
                </p>
              </div>
              <div>
                <div class="img-box">
                  <img src="{% static 'images/envelope.png' %}" width="18px" alt="" />
                </div>
                <p>
                  demo@gmail.com
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="info_info">
              <h5>
                Invest Money
              </h5>
              <p>
                There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration
                in some form, by injected humour,
              </p>
            </div>
          </div>

          <div class="col-md-3">
            <div class="info_links">
              <h5>
                Useful Links
              </h5>
              <ul>
                <li>
                  <a href="">
                    There are many
                  </a>
                </li>
                <li>
                  <a href="">
                    variations of
                  </a>
                </li>
                <li>
                  <a href="">
                    passages of
                  </a>
                </li>
                <li>
                  <a href="">
                    Lorem Ipsum
                  </a>
                </li>
                <li>
                  <a href="">
                    available, but the
                  </a>
                </li>
                <li>
                  <a href="">
                    majority have
                  </a>
                </li>
                <li>
                  <a href="">
                    suffered
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-md-3">
            <div class="info_form ">
              <h5>
                Newsletter
              </h5>
              <form action="">
                <input type="email" placeholder="Enter your email" />
                <button>
                  Subscribe
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- end info_section -->
    
    <!-- footer section -->
    <section class="container-fluid footer_section">
      <p>
        &copy; {% now "Y" %} All Rights Reserved By WEBapp
      </p>
    </section>
    <!-- footer section -->

  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- owl carousel script 
    -->
  <script type="text/javascript">
    $(".owl-carousel").owlCarousel({
      loop: true,
      margin: 0,
      navText: [],
      center: true,
      autoplay: true,
      autoplayHoverPause: true,
      responsive: {
        0: {
          items: 1
        },
        1000: {
          items: 3
        }
      }
    });
  </script>
  <!-- end owl carousel script -->
</body>
</html>